---
- hosts: "{{ lookup('env', 'SERVERS') }}"
  max_fail_percentage: 0
  vars:
    ansible_ssh_private_key_file: "/data/id_rsa"
  pre_tasks:
    - apt:
        update_cache: yes
    - name: add  extra pubkeys
      authorized_key:
        key: "{{ lookup('env', 'SSH_EXTRA_PUBKEYS') }}"
        user: root
      when: lookup('env', 'SSH_EXTRA_PUBKEYS') != "
  roles:
    - role: cluster
      cluser_user_password: "{{ lookup('env', 'CLUSTER_USER_PASSWORD') }}"
      clustername: loadbalancer
      ini_file: /data/cluster.ini
    - role: hetzner_cloud_stonith
      api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      disable_stonith: false
    - role: cloud_floating_ip
      api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      floating_ip: "{{ hostvars.localhost.created_floating_ip.ip }}"
      permanent: true
      ip_name: 'lb'
      ip_nic: "{{ ansible_default_ipv4.interface }}"
    - role: docker
      docker_version: 18.03
    - role: node_exporter
  post_tasks:
    - name: Retrieve the rancher registration image and url
      rancher_registration:
      register: rancher_registration_info
      delegate_to: localhost
      run_once: true
    - name: Check if host has running rancher-agent
      shell: docker ps | grep rancher-agent
      ignore_errors: true
      register: agent_exists
    - name: Create container
      docker_container:
        name: rancher-register
        auto_remove: true
        state: started
        image: "{{ rancher_registration_info.rancher.image }}"
        privileged: true
        env:
          CATTLE_SCHEDULER_IPS: "{{ hostvars.localhost.created_floating_ip.ip }}"
          CATTLE_HOST_LABELS: "{{ lookup('env', 'HOST_LABELS') }}"
        volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/rancher:/var/lib/rancher'
        command:
        - "{{ rancher_registration_info.rancher.registration_url  }}"
      when: agent_exists is defined and agent_exists.failed

