---
- host: localhost
  tasks:
  - name: Create key
    hcloud_ssh_key:
      name: lb_key
      public_key: "{{ lookup('env', 'PUBLIC_KEY') }}"
      state: present
  - name: Create servers
    hcloud_server:
      name: "{{ item }}"
      state: present
      image: debian-9
      server_type: cx11
      location: falkenstein
      ssh_keys:
      - lb_key
    with_list: "{{ servers.split(':') }}"
  - name: List floating ips
    hcloud_floating_ip:
      state: list
    register: list_ips
  - name: Create floating ip
    hcloud_floating_ip:
      description: loadbalancer
      state: present
      type: ipv4
      server: "{% server_list = servers.split(':') %}{{ server_list[0] }}"
    when: "{% for ip in list_ips.floating_ips %}{%%}{% endfor %}{% endfor %}"
  - name: Refresh inventory with new servers
    meta: refresh_inventory
