---
- hosts: localhost
  gather_facts: false
  roles:
    - role: hcloud_create_ip
      ip_description: "{{ lookup('env', 'FLOATING_IP') }}"
    - name: create_ssh_key
      key_path: "{{ lookup('env', 'SSH_KEY_PATH') }}"
  post_tasks:
  - name: Create key
    hcloud_ssh_key:
      name: lb_key
      public_key: "{{ lookup('file', lookup('env', 'SSH_KEY_PATH')+'.pub') }}"
      state: present
  - name: Create servers
    hcloud_server:
      name: "{{ item }}"
      state: present
      image: debian-9
      server_type: cx11
      location: fsn1
      ssh_keys:
      - lb_key
    loop: "{{ lookup('env', 'SERVERS').split(':')|flatten }}"
  - name: Refresh inventory with new servers
    meta: refresh_inventory
